// Generated by tools/blender/build_rimrock.py — do not edit by hand; re-run the builder.
// The rim rampart's collision. It is not a fit to the rock: the rock's footprint is authored *as*
// these circles (NODES/FOOT in the builder) and the mesh is swept off them, so this table is the
// appearance rather than an estimate of it — which is the C3 bar, and `verify` in the builder
// fails the build if the exported mesh and these discs ever drift apart. bulge_mm/gap_mm are the
// measured disagreement: wall outside the stone, and stone outside its wall. Both are millimetre
// scale, against the 90 mm a hand-typed bounding box would have been. Offsets are metres in the
// exported frame (x = radial, z = tangential) about the node origin; `reachT` is how far the cover
// runs along the ring's tangent, which is what decides the pitch that keeps the ring sealed.

export const RIM_ROCK = {
  mega: { h: 4.068, reachT: 3.424, bulge_mm: 3, gap_mm: 0, discs: [
    [0.0, -0.0, 2.62],
    [1.62, 0.28, 1.78],
    [-1.52, -0.72, 1.52],
    [0.3, -1.72, 1.32]
  ] },
  block: { h: 2.875, reachT: 2.553, bulge_mm: 2, gap_mm: 0, discs: [
    [0.0, -0.0, 1.98],
    [1.18, 0.42, 1.3],
    [-1.12, -0.62, 1.1]
  ] },
  slab: { h: 1.532, reachT: 2.04, bulge_mm: 2, gap_mm: 0, discs: [
    [0.0, -0.0, 1.58],
    [0.92, -0.44, 1.02],
    [-0.86, 0.48, 0.92]
  ] },
};
